language: python
python:
  - "3.7"
install:
  - pip --quiet install ansible
before_script:
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg
script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
branches:
  only: [master]
