---

- name: Ensure installation dependencies are installed
  apt:
    name: apt-transport-https
    state: present

- name: Ensure apt key is present
  apt_key:
    url: https://dtcooper.github.io/raspotify/key.asc
    state: present

- name: Ensure apt repository is present
  apt_repository:
    repo: deb https://dtcooper.github.io/raspotify raspotify main
    state: present

- name: Install raspotify
  apt:
    name: raspotify
  become: true

- name: Copy configuration
  template:
    src: "templates/raspotify.j2"
    dest: "/etc/default/raspotify"
  notify:
   - Restart raspotify
